from __future__ import annotations

from .types import Cost, Model

BUILTIN_MODELS: dict[str, dict[str, Model]] = {
    "openai": {
        "gpt-4o": Model(
            id="gpt-4o",
            name="GPT-4o",
            api="openai-responses",
            provider="openai",
            base_url="https://api.openai.com/v1",
            reasoning=False,
            input=["text", "image"],
            cost=Cost(input=2.5, output=10.0, cache_read=1.25, cache_write=0.0),
            context_window=128_000,
            max_tokens=16_384,
        ),
        "gpt-4o-mini": Model(
            id="gpt-4o-mini",
            name="GPT-4o mini",
            api="openai-responses",
            provider="openai",
            base_url="https://api.openai.com/v1",
            reasoning=False,
            input=["text", "image"],
            cost=Cost(input=0.15, output=0.60, cache_read=0.075, cache_write=0.0),
            context_window=128_000,
            max_tokens=16_384,
        ),
        "gpt-5-mini": Model(
            id="gpt-5-mini",
            name="GPT-5 Mini",
            api="openai-responses",
            provider="openai",
            base_url="https://api.openai.com/v1",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=0.25, output=2.0, cache_read=0.025, cache_write=0.0),
            context_window=400_000,
            max_tokens=128_000,
        ),
        "gpt-5.2-codex": Model(
            id="gpt-5.2-codex",
            name="GPT-5.2 Codex",
            api="openai-responses",
            provider="openai",
            base_url="https://api.openai.com/v1",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=1.75, output=14.0, cache_read=0.175, cache_write=0.0),
            context_window=400_000,
            max_tokens=128_000,
        ),
    },
    "anthropic": {
        "claude-3-5-haiku-20241022": Model(
            id="claude-3-5-haiku-20241022",
            name="Claude Haiku 3.5",
            api="anthropic-messages",
            provider="anthropic",
            base_url="https://api.anthropic.com",
            reasoning=False,
            input=["text", "image"],
            cost=Cost(input=0.8, output=4.0, cache_read=0.08, cache_write=1.0),
            context_window=200_000,
            max_tokens=8_192,
        ),
        "claude-sonnet-4-20250514": Model(
            id="claude-sonnet-4-20250514",
            name="Claude Sonnet 4",
            api="anthropic-messages",
            provider="anthropic",
            base_url="https://api.anthropic.com",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=3.0, output=15.0, cache_read=0.30, cache_write=3.75),
            context_window=200_000,
            max_tokens=64_000,
        ),
        "claude-sonnet-4-5": Model(
            id="claude-sonnet-4-5",
            name="Claude Sonnet 4.5 (latest)",
            api="anthropic-messages",
            provider="anthropic",
            base_url="https://api.anthropic.com",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=3.0, output=15.0, cache_read=0.30, cache_write=3.75),
            context_window=200_000,
            max_tokens=64_000,
        ),
        "claude-opus-4-6": Model(
            id="claude-opus-4-6",
            name="Claude Opus 4.6",
            api="anthropic-messages",
            provider="anthropic",
            base_url="https://api.anthropic.com",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=5.0, output=25.0, cache_read=0.5, cache_write=6.25),
            context_window=1_000_000,
            max_tokens=128_000,
        ),
    },
    "azure-openai-responses": {
        "gpt-4o": Model(
            id="gpt-4o",
            name="GPT-4o",
            api="azure-openai-responses",
            provider="azure-openai-responses",
            base_url="",
            reasoning=False,
            input=["text", "image"],
            cost=Cost(input=2.5, output=10.0, cache_read=1.25, cache_write=0.0),
            context_window=128_000,
            max_tokens=16_384,
        ),
        "gpt-4o-mini": Model(
            id="gpt-4o-mini",
            name="GPT-4o mini",
            api="azure-openai-responses",
            provider="azure-openai-responses",
            base_url="",
            reasoning=False,
            input=["text", "image"],
            cost=Cost(input=0.15, output=0.60, cache_read=0.075, cache_write=0.0),
            context_window=128_000,
            max_tokens=16_384,
        ),
        "gpt-5-mini": Model(
            id="gpt-5-mini",
            name="GPT-5 Mini (Azure Responses)",
            api="azure-openai-responses",
            provider="azure-openai-responses",
            base_url="",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=0.25, output=2.0, cache_read=0.025, cache_write=0.0),
            context_window=400_000,
            max_tokens=128_000,
        ),
        "gpt-5.2-codex": Model(
            id="gpt-5.2-codex",
            name="GPT-5.2 Codex",
            api="azure-openai-responses",
            provider="azure-openai-responses",
            base_url="",
            reasoning=True,
            input=["text", "image"],
            cost=Cost(input=1.75, output=14.0, cache_read=0.175, cache_write=0.0),
            context_window=400_000,
            max_tokens=128_000,
        ),
    },
}
